tts:
  - platform: azure_personal_voice
    api_key: YourAPIKey   # Example: 230982340sfsd0fasf2038
    region: YourResourceRegion   # Example: southeastasia)
    voice: YourVoiceModel   # Example: PhoenixLatestNeural
    speaker_profile_id: YourSpeakerProfileID   # Example: 032948309-b32-3029-032948b934
    language: YourLanguage   # Example: en-AU
