tts:
  - platform: azure_tts_custom
    api_key: YourAPIKey
    region: YourResourceRegion
    voice: YourVoiceModel
    speaker_profile_id: Your-Speaker-Profile-GUID
    language: YourLanguage
